openapi: 3.0.0
info:
  title: Trips
  version: '1.0'
  description: Provides Unique Trip ID and Unique Friendly ID / Captures basic trip info
  contact:
    name: Seth Gerou
    email: seth.gerou@noaa.gov
    url: 'https://www.nwfsc.noaa.gov/'
servers:
  - url: 'http://localhost:3000'
paths:
  /trips:
    get:
      summary: trips
      tags:
        - trips
        - trip
      description: list all trips
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/trip.v1.yaml
              examples: {}
      operationId: getTrips
  '/trips/{tripId}':
    parameters: []
    get:
      summary: 'trips/{tripId}'
      tags:
        - trip
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/trip.v1.yaml
      description: get a specific trip
      operationId: getTrip
      parameters:
        - schema:
            type: number
          name: tripId
          in: path
          required: true
